services:
  mongodb:
    image: mongo:7
    container_name: nosql_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16-alpine
    container_name: nosql_pg
    environment:
      POSTGRES_DB: reporting_db
      POSTGRES_USER: report_user
      POSTGRES_PASSWORD: report_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  pg_data:
